Caption_templates = [
    "Can you provide a caption consists of findings for this medical image?",
    "Describe the findings of the medical image you see.",
    "Please caption this medical scan with findings.",
    "What is the findings of this image?",
    "Describe this medical scan with findings.",
    "Please write a caption consists of findings for this image.",
    "Can you summarize with findings the images presented?",
    "Please caption this scan with findings.",
    "Please provide a caption consists of findings for this medical image.",
    "Can you provide a summary consists of findings of this radiograph?",
    "What are the findings presented in this medical scan?",
    "Please write a caption consists of findings for this scan.",
    "Can you provide a description consists of findings of this medical scan?",
    "Please caption this medical scan with findings.",
    "Can you provide a caption consists of findings for this medical scan?",
    "Please generate a medical report based on this image.",
    "Can you generate a diagnose report from this image.",
    "Could you analyze and provide a caption for the findings in this medical image?",
    "Please describe the observations depicted in this medical scan.",
    "Can you summarize the findings of this image in a caption?",
    "What are the significant findings in this medical image?",
    "Please provide a detailed caption outlining the findings of this image.",
    "Could you interpret and describe the findings shown in this medical scan?",
    "What conclusions can you draw from the observations in this image?",
    "Please write a descriptive caption based on the findings in this scan.",
    "What key findings can you identify from examining this medical image?",
    "Could you generate a detailed report based on the observations in this image?",
    "Can you provide a diagnosis based on the findings in this image?",
    "Please generate a comprehensive report summarizing the findings in this image.",
    "Caption the findings in this medical image?",
    "Describe the findings you see.",
    "Caption this medical scan's findings.",
    "What are the findings here?",
    "Describe these findings.",
    "Summarize the findings in these images.",
    "Caption this scan's findings.",
    "Provide a caption for this medical image's findings.",
    "Summarize the findings of this radiograph.",
    "What findings are presented in this scan?",
    "Describe this scan's findings.",
    "Generate a medical report based on this image.",
    "Can you provide a diagnosis based on this image?",
]

abdomen_ct_prompts = [
    "Can you provide a caption consisting of findings for the abdomen organs in this CT scan?",
    "Describe the findings of the abdomen organs in the CT scan you see.",
    "Please caption this CT scan with findings of the abdomen organs.",
    "What are the findings of the abdomen organs in this CT scan?",
    "Describe the abdomen organs in this CT scan with findings.",
    "Please write a caption consisting of findings for the abdomen organs in this CT scan.",
    "Can you summarize with findings the abdomen organs presented in this CT scan?",
    "Please caption this CT scan with findings of the abdomen organs.",
    "Please provide a caption consisting of findings for the abdomen organs in this CT scan.",
    "Can you provide a summary consisting of findings of the abdomen organs in this CT scan?",
    "What are the findings presented in this CT scan of the abdomen organs?",
    "Please write a caption consisting of findings for the abdomen organs in this CT scan.",
    "Can you provide a description consisting of findings of the abdomen organs in this CT scan?",
    "Please caption this CT scan with findings of the abdomen organs.",
    "Can you provide a caption consisting of findings for the abdomen organs in this CT scan?",
    "Please generate a medical report based on the abdomen organs in this CT scan.",
    "Can you generate a diagnostic report from the abdomen organs in this CT scan?",
    "Could you analyze and provide a caption for the findings in the abdomen organs of this CT scan?",
    "Please describe the observations depicted in the abdomen organs of this CT scan.",
    "Can you summarize the findings of the abdomen organs in this CT scan in a caption?",
    "What are the significant findings in the abdomen organs of this CT scan?",
    "Please provide a detailed caption outlining the findings of the abdomen organs in this CT scan.",
    "Could you interpret and describe the findings shown in the abdomen organs of this CT scan?",
    "What conclusions can you draw from the observations in the abdomen organs of this CT scan?",
    "Please write a descriptive caption based on the findings in the abdomen organs of this CT scan.",
    "What key findings can you identify from examining the abdomen organs in this CT scan?",
    "Could you generate a detailed report based on the observations in the abdomen organs of this CT scan?",
    "Can you provide a diagnosis based on the findings in the abdomen organs of this CT scan?",
    "Please generate a comprehensive report summarizing the findings in the abdomen organs of this CT scan.",
    "Caption the findings in the abdomen organs of this CT scan?",
    "Describe the findings you see in the abdomen organs of this CT scan.",
    "Caption this CT scan's findings of the abdomen organs.",
    "What are the findings here in the abdomen organs of this CT scan?",
    "Describe these findings in the abdomen organs of this CT scan.",
    "Summarize the findings in the abdomen organs of these CT scan images.",
    "Caption this CT scan's findings of the abdomen organs.",
    "Provide a caption for this CT scan's findings of the abdomen organs.",
    "Summarize the findings of the abdomen organs in this CT scan.",
    "What findings are presented in the abdomen organs of this CT scan?",
    "Describe this CT scan's findings of the abdomen organs.",
    "Generate a medical report based on the abdomen organs in this CT scan.",
    "Can you provide a diagnosis based on the abdomen organs in this CT scan?",
]

chest_ct_prompts = [
    "Can you provide a caption consisting of findings for the chest organs in this CT scan?",
    "Describe the findings of the chest organs in the CT scan you see.",
    "Please caption this CT scan with findings of the chest organs.",
    "What are the findings of the chest organs in this CT scan?",
    "Describe the chest organs in this CT scan with findings.",
    "Please write a caption consisting of findings for the chest organs in this CT scan.",
    "Can you summarize with findings the chest organs presented in this CT scan?",
    "Please caption this CT scan with findings of the chest organs.",
    "Please provide a caption consisting of findings for the chest organs in this CT scan.",
    "Can you provide a summary consisting of findings of the chest organs in this CT scan?",
    "What are the findings presented in this CT scan of the chest organs?",
    "Please write a caption consisting of findings for the chest organs in this CT scan.",
    "Can you provide a description consisting of findings of the chest organs in this CT scan?",
    "Please caption this CT scan with findings of the chest organs.",
    "Can you provide a caption consisting of findings for the chest organs in this CT scan?",
    "Please generate a medical report based on the chest organs in this CT scan.",
    "Can you generate a diagnostic report from the chest organs in this CT scan?",
    "Could you analyze and provide a caption for the findings in the chest organs of this CT scan?",
    "Please describe the observations depicted in the chest organs of this CT scan.",
    "Can you summarize the findings of the chest organs in this CT scan in a caption?",
    "What are the significant findings in the chest organs of this CT scan?",
    "Please provide a detailed caption outlining the findings of the chest organs in this CT scan.",
    "Could you interpret and describe the findings shown in the chest organs of this CT scan?",
    "What conclusions can you draw from the observations in the chest organs of this CT scan?",
    "Please write a descriptive caption based on the findings in the chest organs of this CT scan.",
    "What key findings can you identify from examining the chest organs in this CT scan?",
    "Could you generate a detailed report based on the observations in the chest organs of this CT scan?",
    "Can you provide a diagnosis based on the findings in the chest organs of this CT scan?",
    "Please generate a comprehensive report summarizing the findings in the chest organs of this CT scan.",
    "Caption the findings in the chest organs of this CT scan?",
    "Describe the findings you see in the chest organs of this CT scan.",
    "Caption this CT scan's findings of the chest organs.",
    "What are the findings here in the chest organs of this CT scan?",
    "Describe these findings in the chest organs of this CT scan.",
    "Summarize the findings in the chest organs of these CT scan images.",
    "Caption this CT scan's findings of the chest organs.",
    "Provide a caption for this CT scan's findings of the chest organs.",
    "Summarize the findings of the chest organs in this CT scan.",
    "What findings are presented in the chest organs of this CT scan?",
    "Describe this CT scan's findings of the chest organs.",
    "Generate a medical report based on the chest organs in this CT scan.",
    "Can you provide a diagnosis based on the chest organs in this CT scan?",
]

pelvis_ct_prompts = [
    "Can you provide a caption consisting of findings for the pelvis organs in this CT scan?",
    "Describe the findings of the pelvis organs in the CT scan you see.",
    "Please caption this CT scan with findings of the pelvis organs.",
    "What are the findings of the pelvis organs in this CT scan?",
    "Describe the pelvis organs in this CT scan with findings.",
    "Please write a caption consisting of findings for the pelvis organs in this CT scan.",
    "Can you summarize with findings the pelvis organs presented in this CT scan?",
    "Please caption this CT scan with findings of the pelvis organs.",
    "Please provide a caption consisting of findings for the pelvis organs in this CT scan.",
    "Can you provide a summary consisting of findings of the pelvis organs in this CT scan?",
    "What are the findings presented in this CT scan of the pelvis organs?",
    "Please write a caption consisting of findings for the pelvis organs in this CT scan.",
    "Can you provide a description consisting of findings of the pelvis organs in this CT scan?",
    "Please caption this CT scan with findings of the pelvis organs.",
    "Can you provide a caption consisting of findings for the pelvis organs in this CT scan?",
    "Please generate a medical report based on the pelvis organs in this CT scan.",
    "Can you generate a diagnostic report from the pelvis organs in this CT scan?",
    "Could you analyze and provide a caption for the findings in the pelvis organs of this CT scan?",
    "Please describe the observations depicted in the pelvis organs of this CT scan.",
    "Can you summarize the findings of the pelvis organs in this CT scan in a caption?",
    "What are the significant findings in the pelvis organs of this CT scan?",
    "Please provide a detailed caption outlining the findings of the pelvis organs in this CT scan.",
    "Could you interpret and describe the findings shown in the pelvis organs of this CT scan?",
    "What conclusions can you draw from the observations in the pelvis organs of this CT scan?",
    "Please write a descriptive caption based on the findings in the pelvis organs of this CT scan.",
    "What key findings can you identify from examining the pelvis organs in this CT scan?",
    "Could you generate a detailed report based on the observations in the pelvis organs of this CT scan?",
    "Can you provide a diagnosis based on the findings in the pelvis organs of this CT scan?",
    "Please generate a comprehensive report summarizing the findings in the pelvis organs of this CT scan.",
    "Caption the findings in the pelvis organs of this CT scan?",
    "Describe the findings you see in the pelvis organs of this CT scan.",
    "Caption this CT scan's findings of the pelvis organs.",
    "What are the findings here in the pelvis organs of this CT scan?",
    "Describe these findings in the pelvis organs of this CT scan.",
    "Summarize the findings in the pelvis organs of these CT scan images.",
    "Caption this CT scan's findings of the pelvis organs.",
    "Provide a caption for this CT scan's findings of the pelvis organs.",
    "Summarize the findings of the pelvis organs in this CT scan.",
    "What findings are presented in the pelvis organs of this CT scan?",
    "Describe this CT scan's findings of the pelvis organs.",
    "Generate a medical report based on the pelvis organs in this CT scan.",
    "Can you provide a diagnosis based on the pelvis organs in this CT scan?",
]
